// Objective-C API for talking to gitlab.com/credify.one/sdks/hdwallet-sdk/go-sdk/src/hdwallet Go package.
//   gobind -lang=objc gitlab.com/credify.one/sdks/hdwallet-sdk/go-sdk/src/hdwallet
//
// File is generated by gobind. Do not edit.

#ifndef __HDWallet_H__
#define __HDWallet_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class HDWalletWallet;

@interface HDWalletWallet : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull mnemonic;
- (NSString* _Nonnull)addSignTx:(NSString* _Nullable)coinType signedTx:(NSString* _Nullable)signedTx;
- (void)clearSecret;
- (NSString* _Nonnull)decrypt:(NSString* _Nullable)cipherText;
- (NSString* _Nonnull)decryptBase64:(NSString* _Nullable)content;
- (NSString* _Nonnull)encrypt:(NSString* _Nullable)plainText;
- (NSString* _Nonnull)getMasterPrivateKey;
- (NSString* _Nonnull)getMasterPublicKey;
- (NSString* _Nonnull)getPrivateKey:(NSString* _Nullable)coinType;
- (NSString* _Nonnull)getPublicKey:(NSString* _Nullable)coinType;
- (NSString* _Nonnull)signMessage:(NSString* _Nullable)message;
- (BOOL)verifySignature:(NSString* _Nullable)signature message:(NSString* _Nullable)message;
@end

FOUNDATION_EXPORT NSString* _Nonnull const HDWalletCustomNet;
FOUNDATION_EXPORT NSString* _Nonnull const HDWalletEosCoin;
FOUNDATION_EXPORT NSString* _Nonnull const HDWalletLocalNet;
FOUNDATION_EXPORT NSString* _Nonnull const HDWalletTestNet;

FOUNDATION_EXPORT HDWalletWallet* _Nullable HDWalletCreateWallet(NSString* _Nullable mnemonic);

FOUNDATION_EXPORT void HDWalletInitSDK(NSString* _Nullable networkName, NSString* _Nullable networkUrl);

#endif
