
// Objective-C API for talking to the following Go packages
//
//	gitlab.com/credify.one/sdks/hdwallet-sdk/go-sdk/src/hdwallet
//
// File is generated by gomobile bind. Do not edit.
#ifndef __HDWallet_FRAMEWORK_H__
#define __HDWallet_FRAMEWORK_H__

#include "HDWallet.objc.h"
#include "Universe.objc.h"

#endif
